# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Emanuele Relmi

[package]
name = "vipervault-core"
version = "0.1.0"
edition = "2024"
authors = ["Emanuele Relmi"]
description = "ViperVault core library (vault format, crypto, memory safety)"
license = "AGPL-3.0-or-later"
repository = "https://github.com/Kirito-Emo/ViperVault"
readme = "../../../README.md"
keywords = ["password-manager", "security", "encryption", "privacy"]
categories = ["cryptography"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.22.0", features = ["serde", "v4"] }
thiserror = "2.0.18"
serde_json = "1.0.149"
zeroize = "1.8.2"
argon2 = "0.5.3"
rand = "0.10.0"
chacha20poly1305 = "0.10.1"
secrecy = { version = "0.10.3", features = ["serde"] }
tokio = { version = "1.50.0", features = ["rt", "macros", "sync", "time", "test-util"] }
fs2 = "0.4.3"
libc = "0.2.183"
tempfile = "3.26.0"
base32ct = "0.3.1"
hmac = "0.12.1"
sha1 = "0.10.6"
sha2 = "0.10.9"
url = "2.5.8"
percent-encoding = "2.3.2"
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["rand_core"] }
hkdf = "0.12.4"